export const SEQ_SCAN_THRESHOLD = 10000;
export const IN_MEMORY_HNSW_THRESHOLD = 50000;
export const DB_HNSW_INDEX_PROPORTION_THRESHOLD = 0.5;

export const VECTOR_SIMILARITY_SEARCH_LIMIT = 10000;
export const HNSW_EF_SEARCH = 200;
export const HNSW_MAX_SCAN_TUPLES = 20000;
export const HNSW_SCAN_MEM_MULTIPLIER = 2;
