export const SEQ_SCAN_THRESHOLD = 1000;

export const HNSW_ISSUE_COUNT_THRESHOLD = 25000;

export const VECTOR_SIMILARITY_SEARCH_LIMIT = 10000;

export const HNSW_EF_SEARCH = 200;
export const HNSW_MAX_SCAN_TUPLES = 20000;
export const HNSW_SCAN_MEM_MULTIPLIER = 2;
