name = "semhub-sync-issue-dev"
main = "./issue.workflow.ts"
compatibility_date = "2024-10-22"       # keep in sync with @cloudflare/workers-types
compatibility_flags = ["nodejs_compat"]
vars = { ENVIRONMENT = "dev" }

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "semhub-sync-issue-workflow-dev"
binding = "SYNC_ISSUE_WORKFLOW"
class_name = "IssueWorkflow"

# Production environment
[env.prod]
name = "semhub-sync-issue-prod"
vars = { ENVIRONMENT = "prod" }

[[env.prod.workflows]]
name = "semhub-sync-issue-workflow-prod"
binding = "SYNC_ISSUE_WORKFLOW"
class_name = "IssueWorkflow"
