name = "semhub-sync-issue-cron-dev"
main = "./cron.workflow.ts"
compatibility_date = "2024-10-22"       # keep in sync with @cloudflare/workers-types
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "semhub-sync-issue-cron-workflow-dev"
binding = "SYNC_ISSUE_CRON_WORKFLOW"
class_name = "IssueCronWorkflow"

# Production environment
[env.prod]
name = "semhub-sync-issue-cron-prod"

[[env.prod.workflows]]
name = "semhub-sync-issue-cron-workflow-prod"
binding = "SYNC_ISSUE_CRON_WORKFLOW"
class_name = "IssueCronWorkflow"
