name = "sync-repo-init"
main = "./index.ts"
compatibility_date = "2024-10-22"       # keep in sync with @cloudflare/workers-types
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "sync-repo-init-workflow"
binding = "SYNC_REPO_INIT_WORKFLOW"
class_name = "SyncWorkflow"
