// Code generated by packages/scripts/src/generate-go.ts. DO NOT EDIT.
package ranking

type RankingConfig struct {
	Weights struct {
		SemanticSimilarity float64
		CommentCount       float64
		Recency            float64
		IssueState         float64
	}
	TimeConstants struct {
		RecencyBaseDays int
	}
	ScoreMultipliers struct {
		OpenIssue   float64
		ClosedIssue float64
	}
}

var Config = RankingConfig{
	Weights: struct {
		SemanticSimilarity float64
		CommentCount       float64
		Recency            float64
		IssueState         float64
	}{
		SemanticSimilarity: 0.8,
		CommentCount:       0.12,
		Recency:            0.05,
		IssueState:         0.03,
	},
	TimeConstants: struct {
		RecencyBaseDays int
	}{
		RecencyBaseDays: 30,
	},
	ScoreMultipliers: struct {
		OpenIssue   float64
		ClosedIssue float64
	}{
		OpenIssue:   1,
		ClosedIssue: 0.8,
	},
}
