name = "semhub-sync-repo-init-dev"
main = "./init.workflow.ts"
compatibility_date = "2024-10-22"       # keep in sync with @cloudflare/workers-types
compatibility_flags = ["nodejs_compat"]
vars = { ENVIRONMENT = "dev" }

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "semhub-sync-repo-init-workflow-dev"
binding = "REPO_INIT_WORKFLOW"
class_name = "RepoInitWorkflow"

[[services]]
binding = "SYNC_EMBEDDING_WORKFLOW"
service = "semhub-sync-embedding-dev"

# UAT environment
[env.uat]
name = "semhub-sync-repo-init-uat"
vars = { ENVIRONMENT = "uat" }

[[env.uat.workflows]]
name = "semhub-sync-repo-init-workflow-uat"
binding = "REPO_INIT_WORKFLOW"
class_name = "RepoInitWorkflow"

[[env.uat.services]]
binding = "SYNC_EMBEDDING_WORKFLOW"
service = "semhub-sync-embedding-uat"

# Production environment
[env.prod]
name = "semhub-sync-repo-init-prod"
vars = { ENVIRONMENT = "prod" }

[[env.prod.workflows]]
name = "semhub-sync-repo-init-workflow-prod"
binding = "REPO_INIT_WORKFLOW"
class_name = "RepoInitWorkflow"

[[env.prod.services]]
binding = "SYNC_EMBEDDING_WORKFLOW"
service = "semhub-sync-embedding-prod"
