// Code generated by packages/scripts/src/generate-go.ts. DO NOT EDIT.
package types

type SearchRequest struct {
	Query string `json:"query"`
	Embedding []float64 `json:"embedding"`
}

type ErrorResponse struct {
	Message string `json:"message"`
	Error interface{} `json:"error,omitempty"`
}

type SuccessResponse struct {
	Message string `json:"message"`
}
