name = "sync-workflow"
main = "./sync.ts"
compatibility_date = "2024-10-22"

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "sync-workflow"
binding = "SYNC_WORKFLOW"
class_name = "SyncWorkflow"
