name = "semhub-installation-dev"
main = "./installation.workflow.ts"
compatibility_date = "2024-10-22"       # keep in sync with @cloudflare/workers-types
compatibility_flags = ["nodejs_compat"]
vars = { ENVIRONMENT = "dev" }

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "semhub-installation-workflow-dev"
binding = "INSTALLATION_WORKFLOW"
class_name = "InstallationWorkflow"

# Production environment
[env.prod]
name = "semhub-installation-prod"
vars = { ENVIRONMENT = "prod" }

[[env.prod.workflows]]
name = "semhub-installation-workflow-prod"
binding = "INSTALLATION_WORKFLOW"
class_name = "InstallationWorkflow"
