name = "semhub-rate-limiter-dev"
compatibility_date = "2024-10-22" # keep in sync with @cloudflare/workers-types
main = "./index.ts"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

[observability]
enabled = true
head_sampling_rate = 0.9

# Production environment
[env.prod]
name = "semhub-rate-limiter-prod"

# Prod needs its own DO binding
[[env.prod.durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

# Prod needs its own migrations
[[env.prod.migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]
