// Code generated by packages/scripts/src/generate-go.ts. DO NOT EDIT.
package main

type LambdaSearchRequest struct {
	Query string `json:"query"`
	Embedding []float64 `json:"embedding"`
}

type LambdaErrorResponse struct {
	Message string `json:"message"`
	Error interface{} `json:"error,omitempty"`
}

type LambdaSuccessResponse struct {
	Message string `json:"message"`
}
